### ISSUE TITLE
libxml2 build error on debian stretch

### ISSUE THREAD

**Issue by ApolloLV** [PADrend/PADrendComplete#3]
I tried building PADrend from source, but for some reason I get the following error during compilation:

```
ninja
[1/796] Building CXX object modules/Util/CMakeFiles/Util.dir/MicroXML.cpp.o
FAILED: modules/Util/CMakeFiles/Util.dir/MicroXML.cpp.o 
/usr/bin/c++   -DUTIL_HAVE_EXECINFO_H -DUTIL_HAVE_GLX_GETPROCADDRESSARB -DUTIL_HAVE_LIB_ARCHIVE -DUTIL_HAVE_LIB_CURL -DUTIL_HAVE_LIB_EGL -DUTIL_HAVE_LIB_FREETYPE -DUTIL_HAVE_LIB_GLX -DUTIL_HAVE_LIB_PNG -DUTIL_HAVE_LIB_SDL2 -DUTIL_HAVE_LIB_SDL2_IMAGE -DUTIL_HAVE_LIB_SDL2_NET -DUTIL_HAVE_LIB_SQLITE -DUTIL_HAVE_LIB_X11 -DUTIL_HAVE_LIB_XML2 -DUTIL_HAVE_LIB_ZIP -DUTIL_HAVE_LIB_ZLIB -DUTIL_HAVE_MALLINFO -DUTIL_HAVE_MALLOC_H -DUTIL_HAVE_MALLOC_INFO -DUTIL_HAVE_OPEN_MEMSTREAM -DUtil_EXPORTS -I/usr/include/x86_64-linux-gnu -I/usr/include/freetype2 -I/usr/include/SDL2 -O2 -g -DNDEBUG -fPIC   -pthread -std=c++11 -MD -MT modules/Util/CMakeFiles/Util.dir/MicroXML.cpp.o -MF modules/Util/CMakeFiles/Util.dir/MicroXML.cpp.o.d -o modules/Util/CMakeFiles/Util.dir/MicroXML.cpp.o -c /home/ahcvs/PADrend/modules/Util/MicroXML.cpp
/home/ahcvs/PADrend/modules/Util/MicroXML.cpp:22:28: fatal error: libxml/globals.h: No such file or directory
 #include <libxml/globals.h>
                            ^
compilation terminated.
[10/796] Building CXX object modules/U.../CMakeFiles/Util.dir/StringUtils.cpp.o
ninja: build stopped: subcommand failed.
```

This happens both with ninja and using makefiles, compiling with GCC.
I installed all debian packages listed, namely libcurl4-openssl-dev, libglew-dev, libopenal-dev, libpng-dev, libsdl2-dev, libsdl2-image-dev, libsdl2-net-dev, libsqlite3-dev, libxml2-dev, libzip-dev, libfreetype6-dev, libarchive-dev, and zlib1g-dev.
I did not build the ThirdParty target since I assumed that these debian packages already contain all that is needed.
The file /usr/include/libxml2/libxml/globals.h does exist, but it seems to me that it is not found at compile time.

What am I doing wrong?

**Comment by ApolloLV** [comment]
I generated the ninja build files with
` cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`

**Comment by MeisterYeti** [comment]
Sound to me, that cmake did not find libxml2 correctly.
Check the output of `cmake -LA | grep LIBXML2`

It should be something like:
```
LIBXML2_INCLUDE_DIR:PATH=/usr/include/libxml2
LIBXML2_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libxml2.so
LIBXML2_XMLLINT_EXECUTABLE:FILEPATH=/usr/bin/xmllint
```

**Comment by ApolloLV** [comment]
It appears that the found folder is correct:
```
cmake -LA | grep LIBXML2
LIBXML2_INCLUDE_DIR:PATH=/usr/include/libxml2
LIBXML2_LIBRARIES:FILEPATH=/usr/lib/x86_64-linux-gnu/libxml2.so
LIBXML2_XMLLINT_EXECUTABLE:FILEPATH=LIBXML2_XMLLINT_EXECUTABLE-NOTFOUND
```

**Comment by MeisterYeti** [comment]
It seems, on some systems, the cmake module for finding libxml2 does not set LIBXML2_INCLUDE_DIRS but only LIBXML2_INCLUDE_DIR (it works for me).
I changed the CMakeLists.txt of the Util submodule & updated PADrendComplete. 
Should work now.
