### ISSUE TITLE
Linker error with undefined references on Archlinux

### ISSUE THREAD

**Issue by ApolloLV** [PADrend/PADrendComplete#5]
I tried building PADrend on my Archlinux machine, since running a VM seems impssible right now (See #4 )
As far as I know, I have all necessary dependencies in their upstream versions.
However, I get an error when linking the successfully compiled components together:

```
make -j 8
[  1%] Built target Geometry
[  7%] Built target EScript
[ 15%] Built target Util
[ 17%] Built target E_Geometry
[ 17%] Built target Sound
[ 22%] Built target GUI
[ 25%] Built target E_Util
[ 34%] Built target Rendering
[ 35%] Built target E_Sound
[ 39%] Built target E_GUI
[ 43%] Built target E_Rendering
[ 77%] Built target MinSG
[100%] Built target E_MinSG
[100%] Linking CXX executable PADrend
/usr/bin/ld: /usr/lib/libSDL2_image-2.0.so.0: undefined reference to `SDL_fmodf'
/usr/bin/ld: /usr/lib/libSDL2_image-2.0.so.0: undefined reference to `SDL_floorf'
/usr/bin/ld: /usr/lib/libSDL2_image-2.0.so.0: undefined reference to `SDL_atan2f'
/usr/bin/ld: /usr/lib/libSDL2_image-2.0.so.0: undefined reference to `SDL_acosf'
/usr/bin/ld: /usr/lib/libharfbuzz.so.0: undefined reference to `FT_Done_MM_Var'
/usr/bin/ld: /usr/lib/libSDL2_image-2.0.so.0: undefined reference to `SDL_fabsf'
/usr/bin/ld: /usr/lib/libSDL2_image-2.0.so.0: undefined reference to `SDL_ceilf'
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[2]: *** [PADrend/CMakeFiles/PADrend.dir/build.make:97: PADrend/PADrend] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:2353: PADrend/CMakeFiles/PADrend.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2
```

My version of SDL2 is 2.0.8-9, of SDL2_image is 2.0.3-1, of harfbuzz is 1.9.0-1.
I already tried reinstalling those, but still the same error occurs.
Does anybody have an idea what might be going wrong?

**Comment by MeisterYeti** [comment]
Strange.
Have you tried building it from source?

**Comment by ApolloLV** [comment]
When building the third party libraries, I encounter a different strange error (see #7 ).
I will try to build only SDL2 from source.

**Comment by ghost** [comment]
I had different errors, but I was able to build in arch by making the following change in `modules/Sound/CMakeLists.txt`:

```
if(SDL2_FOUND)
#	target_include_directories(Sound PRIVATE ${SDL2_INCLUDE_DIRS})
#	target_link_libraries(Sound PRIVATE ${SDL2_LIBRARIES})
	target_link_libraries(Sound PRIVATE SDL2::SDL2)
endif()
```

**Comment by ApolloLV** [comment]
That does not work for me, it complains about not being able to find any SDL2 library then:
```
CMake Error at modules/Sound/CMakeLists.txt:20 (add_library):
  Target "Sound" links to target "SDL2::SDL2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

**Comment by MeisterYeti** [comment]
Try removing the NO_MODULE in the `modules/Sound/CMakeLists.txt` on line 44:
```
# Dependency to SDL2
find_package(SDL2) # remove NO_MODULE here
if(SDL2_FOUND)
	target_include_directories(Sound PRIVATE ${SDL2_INCLUDE_DIRS})
	target_link_libraries(Sound PRIVATE ${SDL2_LIBRARIES})
endif()
```

**Comment by ApolloLV** [comment]
I manually built EP_LIBSDL2, EP_LIBSDL2_IMAGE and EP_LIBSDL2_NET provided in the third party directory, now I was able to remove the libSDL2 errors.
This is verified by the following warning when running CMake:
```
-- Configuring done
CMake Warning at modules/Util/CMakeLists.txt:22 (add_library):
  Cannot generate a safe runtime search path for target Util because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libSDL2_image-2.0.so.0] in /usr/lib may be hidden by files in:
      /[redacted_build_directory]/PADrend/ThirdParty/x86_64-pc-linux-gnu/lib

  Some of these libraries may not be found correctly.


-- Generating done
-- Build files have been written to: /[redacted_build_directory]/PADrend/build

```

**Comment by ApolloLV** [comment]
For future reference: The issue with libharfbuzz.so is the following:
The third_party libraries include Freetype2, which is generated as `ThirdParty/x86_64-pc-linux-gnu/include/freetype2/` as well as `ThirdParty/x86_64-pc-linux-gnu/lib/freetype.so` binaries. This freetype library will call the system harfbuzz. This will produce the error, since the system harfbuzz version varies from the ThirdParty freetype version. This is solved by either using the system freetype binary and system harfbuzz, or building an older version of harfbuzz from source as well. I opted for using the system binaries and simply removed `ThirdParty/x86_64-pc-linux-gnu/include/freetype2` and `ThirdParty/x86_64-pc-linux-gnu/lib/freetype.so*`.
