### ISSUE TITLE
Build error - undefined reference to `FT_Done_MM_Var'

### ISSUE THREAD

**Issue by avimehenwal** [PADrend/PADrendComplete#8]
i was trying to build PADrend on
````
Linux 4.19.13-1-MANJARO x86_64 GNU/Linux
gcc (GCC) 8.2.1 20181127
cmake version 3.13.1
````
but unfortunately I am stuck with the error below while trying to build with `ninja` ([source](https://github.com/PADrend/PADrendComplete))
````
[1/1] Linking CXX executable PADrend/PADrend
FAILED: PADrend/PADrend 
: && /usr/bin/c++  -O2 -g -DNDEBUG  -rdynamic PADrend/CMakeFiles/PADrend.dir/PADrendMain.cpp.o  -o PADrend/PADrend  -Wl,-rpath,/home/avi/Documents/PADrend/build-relwithdebinfo/modules/E_GUI:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/E_MinSG:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/E_Rendering:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/E_Util:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/GUI:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/MinSG:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/Rendering:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/Util:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/E_Geometry:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/EScript:/home/avi/Documents/PADrend/ThirdParty/x86_64-pc-linux-gnu/lib:/home/avi/Documents/PADrend/build-relwithdebinfo/modules/Geometry: modules/E_GUI/libE_GUI.so.0.2.0 modules/E_MinSG/libE_MinSG.so.0.2.0 modules/E_Rendering/libE_Rendering.so.0.2.0 modules/E_Util/libE_Util.so.0.2.0 modules/GUI/libGUI.so.0.2.0 modules/MinSG/libMinSG.so.0.2.0 modules/Rendering/libRendering.so.0.2.0 modules/Util/libUtil.so.0.2.0 modules/E_Geometry/libE_Geometry.so.0.2.0 modules/EScript/libEScript.so.0.7.2 modules/Geometry/libGeometry.so.0.2.0 -Wl,-rpath-link,/home/avi/Documents/PADrend/ThirdParty/x86_64-pc-linux-gnu/lib && :
/usr/bin/ld: /usr/lib/libharfbuzz.so.0: undefined reference to `FT_Done_MM_Var'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
````
[Link to complete error log](https://asciinema.org/a/220925)

Any suggestions how do I fix `FT_Done_MM_Var` reference error?
Super thanks

**Comment by MeisterYeti** [comment]
As far as I know, libharfbuzz is related to libfreetype, so my guess is that the freetype version in ThirdParty is not compatible with your harfbuzz version.
You can either try to update your harfbuzz version, or don't use the ThirdParty libraries and install the required libraries using your package manager.
A list of required packages can be found at https://padrend.github.io/Tutorials/installation_guide.
Although these are for debian based distributions, there should be equivalent packages available.
Unfortunately, I'm not familiar with your Linux distribution and cannot help any further.

**Comment by avimehenwal** [comment]
Seems like new versions of harfbuzz doesn't play very well with other dependencies.
I was able to solve build issue by downgrading to harfbuzz-1.7.4-1 and then again upgrading the package after build.
There was already a thread regarding this on archlinux forum which I should have checked before posting [harfbuzz break after upgrade: undefined symbol:FT_Done_MM_Var](https://bbs.archlinux.org/viewtopic.php?id=234082) 

Thankyou so much for help :)
