### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by ghost** [PADrend/PADrendComplete#9]
I noticed that the desctructor of my custom node is not called after removing it from the scene or reloading the scene. Therefore, I suspect a memory leak. I tested this by reloading the scene mutliple times (repeatedly clicking the "load scene 1" button from the example project), which steadily increases RAM usage (over 1GB after maybe 100 clicks).

**Comment by MeisterYeti** [comment]
If you click  "load scene 1" in the ExampleProject, the scene will not be reloaded. The scene is loaded and added to the current scene list (tree symbol at the top). The old scene will not be deleted. Therefore, it is to be expected that the memory increases.

Why the destructor of your custom node is not called I cannot say without seeing the code. How do you remove it from the scene?

**Comment by ghost** [comment]
Sorry, I must have misunderstood. It works now.
